# Generated by Django 2.0.13 on 2020-01-25 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=100)),
                ('body_text', models.TextField()),
                ('by_auth', models.CharField(max_length=100)),
                ('pub_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
